### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by psequeirag**

### CODE REVIEW

**Comment by mauricio-morales** [comment]
OK. I'd rename "getReader" with "getBufferedReader" as that is the main reason why Java hasn't done this before... we can cherry pick the stack of readers we want with specific features each. So we might end up needing several "getReader" methods to cover different Reader combinations.

**Comment by psequeirag** [comment]
Sorry, I created the pull request prematurely. Let me finish the changes to the README and I'll come back to you comment later.

**Comment by psequeirag** [comment]
Ok, I completed the changes I wanted for the README. It should now be clear what the intent of this library is. Is it good for merge now?

**Comment by psequeirag** [comment]
For the review, I think it should be easier to [look at the final form of the README](../blob/readme/README.md)

**Pull request merged**
